### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by tysongach** [middleman/middleman-directory#185]
Originally reported by @bobwhitelock on the `middlemanapp.com` repo: https://github.com/middleman/middlemanapp.com/issues/720

---

Searching for templates raises an exception and crashes the app; to reproduce:

- Go to https://directory.middlemanapp.com/#/templates/all

- Type something in the search box, e.g. 'blog', or click one of the links below

- An exception is raised and the search does not occur:

```

  main.js:10494 Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at https://directory.middlemanapp.com/javascripts/main.js:10494:75
    at Array.filter (native)
    at o.<anonymous> (https://directory.middlemanapp.com/javascripts/main.js:10493:35)
    at i.b.get (https://directory.middlemanapp.com/javascripts/main.js:4127:22)
    at r (https://directory.middlemanapp.com/javascripts/main.js:3529:14)
    at Ember._ChainNode.b.value (https://directory.middlemanapp.com/javascripts/main.js:3960:28)
    at Ember._ChainNode.b.didChange (https://directory.middlemanapp.com/javascripts/main.js:4005:22)
    at Ember._ChainNode.b.didChange (https://directory.middlemanapp.com/javascripts/main.js:4010:53)
    at v (https://directory.middlemanapp.com/javascripts/main.js:3717:60)
    at Ember.propertyDidChange (https://directory.middlemanapp.com/javascripts/main.js:3708:Th1)

```

This doesn't appear to occur when searching for extensions or services. Thanks

**Comment by bobwhitelock** [comment]
Error still seems to happen at that link
